// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdrUw2yZI4lbPvefjL9gT_8C7JV08qU-4',
    appId: '1:984958945813:web:377dd8ae77058513785c1c',
    messagingSenderId: '984958945813',
    projectId: 'db-hifi',
    authDomain: 'db-hifi.firebaseapp.com',
    storageBucket: 'db-hifi.firebasestorage.app',
    measurementId: 'G-LQ8T2L9LK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDRuqb4DMWZqIx4r2HOBXNmVDkUvNHlMg',
    appId: '1:984958945813:android:cc4aeb460897da45785c1c',
    messagingSenderId: '984958945813',
    projectId: 'db-hifi',
    storageBucket: 'db-hifi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcd4gyDkCE0UBLSqp36MpsDvu8PutxWMM',
    appId: '1:984958945813:ios:170cf3e805746e73785c1c',
    messagingSenderId: '984958945813',
    projectId: 'db-hifi',
    storageBucket: 'db-hifi.firebasestorage.app',
    iosClientId: '984958945813-mbvbpvsi3s5pad6vcq6lhsofag6ckuth.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbHifi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcd4gyDkCE0UBLSqp36MpsDvu8PutxWMM',
    appId: '1:984958945813:ios:170cf3e805746e73785c1c',
    messagingSenderId: '984958945813',
    projectId: 'db-hifi',
    storageBucket: 'db-hifi.firebasestorage.app',
    iosClientId: '984958945813-mbvbpvsi3s5pad6vcq6lhsofag6ckuth.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbHifi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdrUw2yZI4lbPvefjL9gT_8C7JV08qU-4',
    appId: '1:984958945813:web:1b77eb0f359998e4785c1c',
    messagingSenderId: '984958945813',
    projectId: 'db-hifi',
    authDomain: 'db-hifi.firebaseapp.com',
    storageBucket: 'db-hifi.firebasestorage.app',
    measurementId: 'G-KN1X0Z2XRQ',
  );
}
